# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_number', models.CharField(max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_by', models.CharField(max_length=50)),
                ('appraisal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easyname', models.CharField(max_length=50)),
                ('legal_description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=10)),
                ('year_built', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_bday', models.DateTimeField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_renewal', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_rent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('bank_description', models.CharField(max_length=200)),
                ('user_description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Account')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=20)),
                ('sqft', models.IntegerField()),
                ('description', models.TextField()),
                ('bedrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Bedrooms')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Buildings')),
            ],
        ),
        migrations.AddField(
            model_name='tenants',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Units'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Province'),
        ),
        migrations.AddField(
            model_name='appraisals',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Buildings'),
        ),
        migrations.AddField(
            model_name='account_holder',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Province'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reco.Bank'),
        ),
    ]
