# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='buildings',
            old_name='easyname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='buildings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Buildings'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='moveout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Bank'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='appraisal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='contract_renewal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='current_rent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='tenant_bday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reco.Building_Category'),
        ),
    ]
