# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_account_holder_entry_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder'),
        ),
        migrations.AlterField(
            model_name='account_holder',
            name='entry_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='building_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reco.Building_Category'),
        ),
    ]
