# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_auto_20171029_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Tenants')),
            ],
        ),
    ]
