# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0005_tenant_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_payments',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reco.Revenue_Category'),
        ),
    ]
