# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0009_auto_20171112_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
