# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0013_personal_shareholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='personal_shareholder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reco.Personal_Shareholder'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='reco.Shareholder_Type'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder'),
        ),
    ]
