# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0017_auto_20171112_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='personal_shareholder',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='shareholder',
        ),
    ]
