# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0018_auto_20171112_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='corporate_sh',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Shareholder'),
        ),
        migrations.AddField(
            model_name='shares',
            name='personal_sh',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Personal_Shareholder'),
        ),
    ]
