# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0019_auto_20171112_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate_Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('number_of_shares', models.IntegerField()),
                ('price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder')),
                ('corporate_sh', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Shareholder')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Shares_Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('number_of_shares', models.IntegerField()),
                ('price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Account_Holder')),
                ('personal_sh', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reco.Personal_Shareholder')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Shares_Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='shares',
            name='company',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='corporate_sh',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='personal_sh',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='Shares',
        ),
    ]
