# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-13 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0020_auto_20171112_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporate_shares',
            old_name='corporate_sh',
            new_name='shareholder',
        ),
        migrations.RenameField(
            model_name='personal_shares',
            old_name='personal_sh',
            new_name='shareholder',
        ),
    ]
